### ISSUE TITLE
Rules re: architecture?

### ISSUE THREAD

**Issue by nemo** [keen/keen-tracking.js#1]
Hey,

This is pretty cool! Might be able to help out here as I'm experimenting with some stuff on our own [SDK](https://github.com/taplytics/Taplytics-js).

Is it possible to setup a more firm structure around the following:

- External libraries: e.g.are we able to use jQuery/Zepto/etc. or not?
- Functions: a template for how we should create one of the proposed functions. (it can get pretty messy otherwise)
- More clear goals of where you want to take this project (lots of possible overlap of where keen-js is/should be + common-web)

Nima

**Comment by dustinlarimer** [comment]
@nemo awesome idea! I'm going to add single/multi event tracking functionality, so I'll scaffold out some files and guidelines.

**Comment by dustinlarimer** [comment]
@nemo first pass at a better-defined project structure: https://github.com/keen/keen-tracking.js/commit/16b5bd62ed014a3dd58a6794bded402bbc2a71b4

**Comment by nemo** [comment]
@dustinlarimer – much better. This should help people contribute better / in small chunks. Might take a look at a couple of the functions this week and send a PR your way.

**Comment by dustinlarimer** [comment]
@nemo sounds great! made some progress today, got a lot of boilerplate stuff out of the way. should have plenty to run with now!
