### ISSUE TITLE
node utils.cookie is undefined

### ISSUE THREAD

**Issue by camel113** [keen/keen-tracking.js#107]
I try to set `utils.cookie` like your example in the Readme but I get the error  

> KeenTracking.utils.cookie is not a function

I am using it exactly like this

```
const express = require('express')
const app = express()
var KeenTracking = require('keen-tracking');

var client = new KeenTracking({
  projectId: 'x',
  writeKey: 'x'
});

const utils = KeenTracking.utils;

var sessionCookie = KeenTracking.utils.cookie('cookie-session-test')
```
It looks like `cookie` is not available.

**Comment by adamkasprowicz** [comment]
Thank you for pointing that out. Some of the .utils are available only for the browser version of keen-tracking.
I've updated Readme, so we can avoid confusion in the future
https://github.com/keen/keen-tracking.js#api-nodejs-server-side-tracking-back-end
