### ISSUE TITLE
input with name of 'submit' generates error

### ISSUE THREAD

**Issue by lecar-red** [keen/keen-tracking.js#108]
this is an odd one :)

When using `keen-tracking-1.4.0.js` for general web tracking, an element of type `submit` with name of `submit` (`<input name="submit" type="submit" value="Go">`) generates following console error and then prevents form from submitting:

`Uncaught TypeError: t.submit is not a function
    at keen-tracking-1.4.0.min.js:1`

as a side note, if the name is `Submit` (note capital 'S') then it works fine.

**Comment by adamkasprowicz** [comment]
Hi Lecar-red,
Thank you for reporting, but it's default behaviour of the browser :)
https://stackoverflow.com/questions/833032/submit-is-not-a-function-error-in-javascript
Please change name of the submit button to anything else and it will work
