### ISSUE TITLE
Support v2 of Youtube analytics api

### ISSUE THREAD

**Issue by pandemicsyn** [keen/keen-tracking.js#121]
Youtube is discontinuing support for v1 of the YouTube analytics api on October 31st.  We should check to see what if any changes are required for https://keen.io/docs/streams/video-tracking/#youtube-video-tracking.

YouTube's made a migration guide is available here - https://developers.google.com/youtube/analytics/migration

**Comment by adamkasprowicz** [comment]
No changes needed, because our youtube video tracking example is based on iframe_api https://developers.google.com/youtube/iframe_api_reference
