### ISSUE TITLE
CDN dist version is sometimes one behind actual version

### ISSUE THREAD

**Issue by EyePulp** [keen/keen-tracking.js#147]
This may not be an issue, and I might be screwed up, but the version URL from the CDN is one ahead of the actual version (or the version value) being distributed:

- https://cdn.jsdelivr.net/npm/keen-tracking@4.0.8 =>  `exports={name:"keen-tracking",version:"4.0.7"...}`

- https://cdn.jsdelivr.net/npm/keen-tracking@4.0.7 =>  `exports={name:"keen-tracking",version:"4.0.6"...}`

- https://cdn.jsdelivr.net/npm/keen-tracking@4.0.6 =>  `exports={name:"keen-tracking",version:"4.0.5"...}`

**Comment by adamkasprowicz** [comment]
it's fixed in keen-tracking@4.0.12, thanks for reporting!
