### ISSUE TITLE
Option to customise pageViewsOnExit beforeunload listener

### ISSUE THREAD

**Issue by vliegenthart** [keen/keen-tracking.js#149]
I'm using Keen auto tracking with pageviewsOnExit enabled, but am running into an issue with unwanted `pageviews` event being recorded. This is caused by a PDF download button on my website, which sets the `window.location.href` in order to download a PDF, and thus triggers an unwanted `pageviews` event, without actually leaving the page from a user's perspective.

Is there any known workaround available, and if not, is there a different way I could approach this?

**Comment by adamkasprowicz** [comment]
Hi! Add "download" attribute to your PDF link
```HTML
<a download href="some_file.pdf">Some File</a>
```

https://stackoverflow.com/a/26922732/9548485
