### ISSUE TITLE
Changelog or Release Notes

### ISSUE THREAD

**Issue by isTravis** [keen/keen-tracking.js#152]
Thanks for all your work on Keen. Perhaps this is on your website somewhere, and I'm missing it - but are there release notes or a changelog? I'm updating from 3.2 to 4.0 and I can't find what new features or breaking changes are behind the major version change.

Thanks!

**Comment by adamkasprowicz** [comment]
Hi @isTravis

Thanks for reporting! I've just updated the release notes - https://github.com/keen/keen-tracking.js/releases/tag/v4.0.0
The biggest change was that we removed jsonp and xhr support from the package. Now we rely on the Fetch API.

PS: We're open for suggestions - is there anything missing in the package that would make your life easier?

Regards!

**Comment by isTravis** [comment]
Awesome - thanks so much! I notice now on the second page of releases that you have notes on earlier v3.x releases. Apologies if I missed some of the v4 notes there!

Nothing else comes to mind at the moment for usability suggestions - I'll be sure to file an issue if something comes up!

**Comment by isTravis** [comment]
The [Releases page](https://github.com/keen/keen-tracking.js/releases?after=v4.0.5) does have more release notes for older versions. Adam linked directly to 4.0.0 to respond directly to my question. I agree though that Apache's release notes are nicely structured and would be really helpful.

**Comment by adamkasprowicz** [comment]
@josh-m-sharpe , thank you for the suggestion. We'll add more detailed release notes in the future!
