### ISSUE TITLE
keen-tracking optout convenience method

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/keen-tracking.js#164]
Its easy to build tracking optout functionality with keen-tracking, but we should make it easy for Keen users and just create a simple wrapper that does something along these lines:

when 
```javascript
client.setOptOut(true)
```
is called persists the option to localStorage, and on page load checks if optout=true and if so disables tracking of user.

--- 
you can also pass optOut value directly in the config object like:
```javascript
const client = new KeenTracking({
  projectId: 'PROJECT_ID',
  writeKey: 'WRITE_KEY',
  optOut: true
});

```

**Comment by apryka** [comment]
this feature has been implemented in version [4.3.0](https://github.com/keen/keen-tracking.js/releases/tag/v4.3.0)
