### ISSUE TITLE
respect navigator.donottrack

### ISSUE THREAD

**Issue by adamkasprowicz** [keen/keen-tracking.js#167]
Implement
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack

```
const client = new KeenTracking({
  projectId: 'PROJECT_ID',
  writeKey: 'WRITE_KEY',
  respectDoNotTrack: true // by default it's false
});
```

**Comment by apryka** [comment]
enhancement has been implemented in version [4.3.0](https://github.com/keen/keen-tracking.js/releases/tag/v4.3.0)
