### ISSUE TITLE
Script throws an exception if localStorage is disabled

### ISSUE THREAD

**Issue by dpashkevich** [keen/keen-tracking.js#177]
Steps to reproduce:
* In Chrome or Firefox, do one of the following:
  1. disable cookies and open a page with keen-tracking.js loaded 
OR
  2. disable third party cookies and embed a page with keen-tracking.js into a different domain

Expected result:
* The page with keen tracking loads fine

Actual result:
* Exception is thrown:
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

This breaks applications that use keen-tracking or a package that depends on it (like Prod Perfect).

The offending line is:
https://github.com/keen/keen-tracking.js/blob/82dd35b94a99069b9968eb0d74fc320a840fc25e/lib/browser.js#L104

```
if (localStorage && localStorage.getItem('optout')) {
  KeenCore.optedOut = true;
}
```

This code will fail if `window.localStorage` exists, but access to it is denied (or, for instance, if localStorage is full). The code should check for localStorage availability in a different way, for example:

```
function lsTest(){
    var test = 'test';
    try {
        localStorage.setItem(test, test);
        localStorage.removeItem(test);
        return true;
    } catch(e) {
        return false;
    }
}

if(lsTest() === true){
    // available
}else{
    // unavailable
}
```

Source: https://stackoverflow.com/questions/16427636/check-if-localstorage-is-available

**Comment by adamkasprowicz** [comment]
Hi @dpashkevich 
Thank you for reporting the issue and providing example how to fix it. We'll publish the fix tomorrow.

**Comment by adamkasprowicz** [comment]
@4.4.1
