### ISSUE TITLE
Packaging Issue with 4.5.1

### ISSUE THREAD

**Issue by Miguel-Alberto** [keen/keen-tracking.js#197]
<img width="967" alt="image" src="https://user-images.githubusercontent.com/36014895/105783865-85f8f680-5f45-11eb-9e47-0dfe655e748d.png">

Looks like you may have a hard coded path to a source map @apryka - this does not happen in earlier versions of the library.

**Comment by apryka** [comment]
@Miguel-Alberto fixed in [4.5.2](https://github.com/keen/keen-tracking.js/releases/tag/v4.5.2)

**Comment by Miguel-Alberto** [comment]
👍 Thanks!
