### ISSUE TITLE
Changelog is missing for 5.0

### ISSUE THREAD

**Issue by stof** [keen/keen-tracking.js#211]
https://github.com/keen/keen-tracking.js/releases does not have the release notes for versions newer than 4.5.1

**Comment by maciejrybaniec** [comment]
Hi @stof,

Thank You for the information - we'll update changelog for releases.

**Comment by stof** [comment]
@apryka @maciejrybaniec any news on that one ?

**Comment by maciejrybaniec** [comment]
@stof Sorry for late response - I've created changelog for version 5.0
