### ISSUE TITLE
Missing tag name

### ISSUE THREAD

**Issue by garethtdavies** [keen/keen-tracking.js#35]
I think you are missing the name of the tag here in the text below on README.md. Above which tag should the snippet be pasted?

`Copy/paste this snippet of JavaScript above the tag of your page to load the tracking library asynchronously.`

**Comment by dustinlarimer** [comment]
@garethtdavies nice catch - that would be the closing `</head>` tag.

**Comment by dustinlarimer** [comment]
Fixed: https://github.com/keen/keen-tracking.js/commit/6ec36d65babf1c7c101c766039be50d6c1157848, thanks!
