### ISSUE TITLE
Suggestion: cookie.set could return value instead of this

### ISSUE THREAD

**Issue by mijamo** [keen/keen-tracking.js#48]
A very common use case with cookie is to try to get it, and if it does not exist set it instead.

As there is no function `getOrSet`, it would be great if `set`would return the value instead of `this`so that we could do that:

`const userID = sessionCookie.get('user_id') || sessionCookie.set('user_id', Keen.helpers.getUniqueId())`

Is there any internal reason for having set return this ? I haven't found any use case for that.

**Comment by dustinlarimer** [comment]
@mijamo that's a fair question and suggestion. The purpose for returning `this` for modification tasks is that it makes these methods chainable:

```javascript
const cookie = Keen.utils.cookie('user_id')
  .options({ ... })
  .expire(14)
  .set({
    // ...
  })
```

If you tack another `.get('user_id')` after `.set()` I think you would get the same result that you're looking for:

```javascript
const userID = sessionCookie.get('user_id') || sessionCookie.set('user_id', Keen.helpers.getUniqueId()).get('user_id')
```

Would that do the trick?

**Comment by mijamo** [comment]
Yes this is what I ended up doing. I understood the chainable necessity for `options` or `expire` but a bit less for `set` which in my mind was always at the end of the chain, but I also understand it may be useful in some cases.

**Comment by dustinlarimer** [comment]
thanks @mijamo!
