### ISSUE TITLE
Document that `getDatetimeIndex()` default is *not* UTC

### ISSUE THREAD

**Issue by felliott** [keen/keen-tracking.js#49]
Hello!

When I started using `getDatetimeIndex()`, I assumed that it would be returning the time for UTC.  I had to read the MDN page for Date() to realize that it was browser-local time.  I think it would be handy to document this and perhaps also show how to get the DT in UTC[1]:

```
var now = new Date(); 
var now_utc = new Date(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(),  now.getUTCHours(), now.getUTCMinutes(), now.getUTCSeconds());
var utcDatetimeIndex = Keen.helpers.getDatetimeIndex(now_utc);
```

Thank you for your time and effort on this!

Cheers,
Fitz

[1] Adapted from: http://stackoverflow.com/a/6777470

**Comment by dustinlarimer** [comment]
@felliott that's a great idea! Perhaps that could just be a different/new helper function, like `Keen.helpers.getDatetimeIndexUTC()`?

**Comment by felliott** [comment]
@dustinlarimer That would be awesome!  I'm currently tracking both, so having an additional helper would be great.

Cheers,
Fitz

**Comment by dustinlarimer** [comment]
@felliott thanks again for this comment. I'll roll a note into the README today. 

Also, the API now supports this functionality as an add-on! Learn more here: https://keen.io/docs/api/#datetime-parser
