### ISSUE TITLE
minor: inconsistent use of snake_case and camelCase in library

### ISSUE THREAD

**Issue by felliott** [keen/keen-tracking.js#50]
Hello!

Most of your documentation uses snake_case key names in events.  The `getDatetimeIndex()` helper, and the `ip_to_geo`, `ua_parser`, and `url_parser` addons all add fields to the event with snake_cased names.  However, the `getScreenProfile()` helper adds camelCased keys (`colorDepth`, `availHeight`, etc.) to the event.  It's a minor thing, but it would be nice if there was one consistent casing used for documentation and keen-provided addons and helpers, so that when we're writing queries, we don't have to remember which casing applies to which keys.  Thank you!

Cheers,
@felliott

**Comment by dustinlarimer** [comment]
nice catch @felliott 👍 

Unfortunately this will need to stay as-is, as it's already woven into folks' data models and breaking it would have a pretty significant impact on anyone already using this. Thanks for the heads up, just the same!
