### ISSUE TITLE
 recordDeferredEvents() sends queued events in bulk, but doesn't handle individual event errors

### ISSUE THREAD

**Issue by dorkusprime** [keen/keen-tracking.js#52]
recordDeferredEvents() utilizes the bulk tracking function, but flushes the entire queue – if an individual event is malformed (or fails for any other reason), it is lost forever.

Current implementation for reference:

``` javascript
    self.recordEvents(currentQueue.events, function(err, res){
      if (err) {
        // Retry once
        self.recordEvents(currentQueue.events);
      }
      else {
        currentQueue = void 0;
      }
    });
```

A proposed solution would be to walk through the entries in the Keen response, and emit some sort of failure for each invalid event (so the developers can implement any sort of notification/handling they wish).

**Comment by dorkusprime** [comment]
Note: This is closely related to https://github.com/keen/keen-tracking.js/issues/51

**Comment by adamkasprowicz** [comment]
Is it still a valid issue?
During the last 2 years we added a lot of fixes to our API endpoint to handle all kinds of input. Keen-tracking is supporting request-retries if there is a connection issue.
There's no easy way to handle saving each event of the bulk without accepting huge performance drop.
