### ISSUE TITLE
Base64 data attributes are not url encoded

### ISSUE THREAD

**Issue by josephwegner** [keen/keen-tracking.js#53]
Base64 strings occasionally contain special characters (most notably, `+`). Right now keen-tracking does not URL Encode the base64 encoded `data` attribute before sending it. In certain scenarios this causes the URL to break, and the Keen API barfs.

**Comment by dustinlarimer** [comment]
Has this been resolved by #59?

**Comment by josephwegner** [comment]
Yerp.
