### ISSUE TITLE
writePath config option ignored

### ISSUE THREAD

**Issue by Ramblurr** [keen/keen-tracking.js#57]
The README claims there is a `writePath` config property:

> ```
> `writePath: '/3.0/projects/YOUR_PROJECT_ID/events'`
> ```
> 
> host and writePath: these options can be overwritten to make it easier than ever to proxy events through your own intermediary host.

Yet it seems completely ignored. Searching the codebase for writePath only find matches in the README.

**Comment by dustinlarimer** [comment]
Yeah, this was dropped in favor of using the `client.url()` method and internal resources config for building URLs. The issue was that this `writePath` design made it super difficult to customize the URL when proxying writes through an intermediary service. I suppose this wording should be removed from the README file. Nice catch!

**Comment by Ramblurr** [comment]
What's the recommended way to achieve "writepath" like features?

We're proxying writes through our own server, and it doesn't use the /3.0/projects/... url format.

So to override the path I am doing this very hacky thing

```js
var writePath = "/api/analytics/events"; // our custom prefix
client.config.resources.events = client.config.resources.events.replace("/3.0/projects/{projectId}/events", writePath);
```

**Comment by dustinlarimer** [comment]
@Ramblurr these resources are managed via the internal `resources` map you found, and can be accessed w/ the `client.resources()` method. This map is used to construct URLs with `client.url('some-key')`. We've named the defaults according to corresponding API resources.

Here are a few examples:

```javascript
{
  'projectId': '{protocol}://{host}/3.0/projects/{projectId}',
  'events': '{protocol}://{host}/3.0/projects/{projectId}/events'
}
```

Those values wrapped in brackets are replaced with matching props from the client instance's configuration. This is all meant to create some options with regard to building out URLs.

You can rewire (and then access) the `events` endpoint like so:

```javascript
client.resources({
  'events': '{protocol}://{host}/api/analytics/events'
});

client.url('events');
// returns https://your-host.com/api/analytics/events
```

You could also just hardwire the protocol and host in this way too, if you prefer.

Does this help answer the question? Sorry for the speed-bump!

**Comment by dustinlarimer** [comment]
@Ramblurr was this answer helpful? Closing for now, but please let me know if I can add any more info or context here-
