### ISSUE TITLE
Create Keen.deferDomEvents function to manage default DOM event timeouts

### ISSUE THREAD

**Issue by Ramblurr** [keen/keen-tracking.js#58]
The readme mentions the `Keen.deferDomEvents` function, but it doesn't seem to exist in the codebase.

**Comment by dustinlarimer** [comment]
Hey @Ramblurr - thanks for posting. It's listed as a "todo" at the moment. Is this something you would find useful?

**Comment by dustinlarimer** [comment]
Removing this feature from our roadmap for this SDK.
