### ISSUE TITLE
disabling event logging

### ISSUE THREAD

**Issue by brandonmp** [keen/keen-tracking.js#60]
I'm trying to turn off event-logging in `dev` environment, but `Keen.enabled = false` doesn't seem to do the trick (as evidenced by viewing my collections in the keen dash). Is there another step I have to take?

The project is `react` using `webpack`
```

// keen-config.js
import Keen from 'keen-tracking'
export const initKeen = () => {
    const client = new Keen({
        projectId,
        writeKey,
    })

    const sessionCookie = Keen.utils.cookie('wayhome-cookie')
    if (!sessionCookie.get('visitorID')) {
        sessionCookie.set('visitorID', Keen.helpers.getUniqueId())
    }
    const sessionID = Keen.helpers.getUniqueId()
    const sessionTimer = Keen.utils.timer()
    sessionTimer.start()
    client.extendEvents(() => {
       // yadda yadda yadda
    })
 return client
}


// index.js
const client = initKeen()
window.Keen = client
if (process.env.NODE_ENV === 'development') {
    console.log("DISABLING KEEN") 
    Keen.enabled = false
}

```

The `console.log` statement fires, so I know my conditional is working.

**Comment by dustinlarimer** [comment]
@brandonmp it appears you're replacing `window.Keen` with the client instance returned by `initKeen()`. How about setting `window.Keen = Keen` in `initKeen()`, and then deciding whether or not to disable it there?

**Comment by brandonmp** [comment]
sorry, should have clarified--i'm loading `keen` through the `npm module`, not the `script` tag in the browser `head`


is the `client` returned by `new Keen({})` not affected by toggling `Keen.enabled` ? As near as I can tell, all other `Keen` functions work fine, so my assumption was that my initialization method was resulting in the same `Keen` global object that the `script` tag method would've.

**Comment by dustinlarimer** [comment]
No problem at all -- in the example above, `initKeen()` returns the `client` instance. This isn't the global, but is rather an instantiated object, since `Keen` is a constructor. `new Keen({ ... })` returns a client instance, not the global itself. Does this help?

**Comment by dustinlarimer** [comment]
Re: ETA- give this a try-

```javascript
import Keen from 'keen-tracking'
window.Keen = Keen
if (process.env.NODE_ENV === 'development') {
    console.log("DISABLING KEEN") 
    Keen.enabled = false
}

// Instantiate a client instance
const client = new Keen({ ... });

// Call methods of that instance
client.addEvent('collection', { ... }, () => { ... });
```

**Comment by brandonmp** [comment]
Ahh got it, yeah that's a big help, thanks dustin.

re: instantiated client, does calling `Keen.recordEvent` then invoke the instantiated client?  in other words, would the `recordEvent()` call in `otherFile.js` in this example employ the already-instantiated client? 

```
// keen-config.js
import Keen from 'keen-tracking'
window.Keen=Keen
const client = new Keen({...})


// otherFile.js
Keen.recordEvent({...})
```

Hoping to avoid repeated instantiations, as (afaik) that would screw-up whatever `context` i'm tracking

**Comment by dustinlarimer** [comment]
The `recordEvent` method is part of the instance itself, so it would look like this:

```javascript
client.recordEvent('collection-name', { ... });
```

**Comment by brandonmp** [comment]
okay got it. it sounds like my best option here is to put both the client instance _and_ the `Keen` object in the `window` object if i want to be able to cancel logging and `recordEvent` from anywhere in the project. thanks, dustin.

**Comment by dustinlarimer** [comment]
That's certainly one approach! I'm not sure how your data store is set up, but if you're using a dispatcher/event emitter pattern you could also centralize a lot of this as state, keeping data modeling and calls to our API in one manageable place. 

We wire up tracking for our own React apps with standalone scripts that register with a given app's `appDispatcher` and triggering API calls based on various actions. Here's an example from our own Explorer app, where `client` is an instance as we've discussed above:

```javascript
window.explorer.appDispatcher.register(function(action) {
  switch(action.actionType) {
    case 'EXPLORER_QUERY_SUCCESS':
      client.recordEvent('Explorer query', {
        resultType: 'success',
        query: action.query || {},
        isSaved: action.isSaved
      });
      break;
      
    // ...
```

**Comment by brandonmp** [comment]
ah cool, that's clever. 

i'm doing something similar in my web app--it's just regular `redux/redux-saga/react`, so i just track whichever actions i care about from a `saga`.  

questions in this thread are more for a project i have that uses [`gatsby-js`](https://github.com/gatsbyjs/gatsby) & no `redux` or central app state to speak of (short of `react context`). 

`gatsby` evaluates all the project's code before rendering it to static `html`, so I was having some trouble initializing snippets in the `index.html`'s  `<head>` tag. so, jamming the `client` and `Keen` into `window` felt reasonable--glad to hear it's at least a feasible approach
