### ISSUE TITLE
Version 1.0.5 in the CDN

### ISSUE THREAD

**Issue by mijamo** [keen/keen-tracking.js#62]
Hello,

The new version 1.0.5 doesn't seem to be available in a Keen CDN, or at least I haven't found any link to it (`https://d26b395fwzu5fz.cloudfront.net/keen-tracking-1.0.5.min.js` returns a 403 for instance).

Would be nice if the new version was available and the documentation updated in consequence.

**Comment by tbarn** [comment]
Hey @mijamo! I am checking in on this right now.

**Comment by tbarn** [comment]
Just updated with this commit: https://github.com/keen/keen-tracking.js/commit/833f23fb12afc0b122910a38b732d4cd0bccfead

Thanks for pointing it out! ✨
