### ISSUE TITLE
client.recordEvents giving ResourceNotFoundError

### ISSUE THREAD

**Issue by monvillalon** [keen/keen-tracking.js#66]
Using version 1.1.2 of keen-tracking I'm getting an error when trying to use recordEvents.

I've tracked it down to a POST request to
**https://api.keen.io/3.0/projects/XXXXXXXX/events/**

That returns the result
```
{
  "message": "Resource not found.",
  "error_code": "ResourceNotFoundError"
}
```

Trying the same request on POSTMAN, it works if I remove the trailing slash
**https://api.keen.io/3.0/projects/XXXXXXXX/events**

**Comment by jnacier** [comment]
+1 The trailing slash is definitely the cause of this error

**Comment by dustinlarimer** [comment]
@monvillalon @jnacier thank you for catching this and reporting, I'll get a patch ready 👍

**Comment by dustinlarimer** [comment]
@monvillalon @jnacier `keen-tracking@1.1.3` is out now with the patch. Please let me know if you hit any other speed bumps! Thanks again! 👍
