### ISSUE TITLE
IP to Geo parser and dynamic IPs don't play ball

### ISSUE THREAD

**Issue by sbl** [keen/keen-tracking.js#69]
As per documentation:

> input: An object with a key of “ip” and a value of the name of the property containing the IP address to parse.
> This add-on can be used with the dynamic IP address placeholder.

This doesn't work and results in a 400:

```javascript
{
   ...anyEvents,
    keen: {
      addons: [
        {
          name: 'keen:ip_to_geo',
          input: {
            ip: '${keen.ip}',
          },
          output: 'geo',
        },
]
```

This works:

```javascript
{
   ...anyEvents,
    my_ip: '${keen.ip}',
    keen: {
      addons: [
        {
          name: 'keen:ip_to_geo',
          input: {
            ip: 'my_ip',
          },
          output: 'geo',
        },
]
```

am I doing it wrong?

**Comment by dustinlarimer** [comment]
@sbl the working example you referenced here is the correct way to do it.. the dynamic placeholder needs to be assigned in the event body, and then the add-on should reference that property. Perhaps there's an error in our docs?

**Comment by sbl** [comment]
Ok thanks. The 2nd paragraph in the docs I quoted was a little misleading then: this is what made me think version 1 could also work.

**Comment by dustinlarimer** [comment]
@sbl thanks for the heads up on this - can you share the link to the page where this is vague? We'll get it fixed up 👍

**Comment by sbl** [comment]
https://keen.io/docs/api/?shell#ip-to-geo-parser

**Comment by dustinlarimer** [comment]
Thanks, we'll get this fixed up!

**Comment by dustinlarimer** [comment]
Docs have been updated appropriately- thanks again for reporting!
