### ISSUE TITLE
listener functionality doesn't bind to nodes as expected

### ISSUE THREAD

**Issue by aroc** [keen/keen-tracking.js#72]
The `listener` helper doesn't seem to bind events as expected. Example showing behaviour:
https://jsfiddle.net/266agghe/8/

**Comment by dustinlarimer** [comment]
@aroc looks like events on child elements aren't captured. Changing the selector to account for the child nodes does work:

```javascript
var firstLink = Keen.utils.listener('#my-link strong');
```

**Comment by aroc** [comment]
@dustinlarimer we should probably bubble these up. If you have something with multiple child elements, you'd end up needing to select on all of them. Such as `<strong>`, `<i>`, `<span>` etc.

**Comment by dustinlarimer** [comment]
Interestingly enough, using a wildcard `'#my-link *'` does work too..

**Comment by dustinlarimer** [comment]
I think I like that behavior.. not sure if assuming a wildcard would cause other issues, or if we should update docs to articulate this..

**Comment by aroc** [comment]
Wildcard might be a good option here! I can totally make use of that. Nice find. If we update the docs we're probably good on this front for now. 💃
