### ISSUE TITLE
Give us a way to stop the queue interval

### ISSUE THREAD

**Issue by gfpacheco** [keen/keen-tracking.js#76]
I'm writing a seed script that records some predefined events for development purpose. But the script never finishes, and I was stuck for a few hours until I find out that this lib sets an interval and that prevents node process from exiting.

It would be great if I could stop that interval when my script finishes sending the events so that the process can exit normally.

For now I'm forcing `process.exit()` when I'm done.

**Comment by dustinlarimer** [comment]
@gfpacheco thanks for reporting -- where exactly is this interval set?

**Comment by dustinlarimer** [comment]
Perhaps here? https://github.com/keen/keen-tracking.js/blob/master/lib/utils/timer.js#L14

**Comment by gfpacheco** [comment]
[Here](https://github.com/keen/keen-tracking.js/blob/04e5bef342609c77ab7bb3c97562cf9686632e58/lib/utils/queue.js#L24) actually

**Comment by dustinlarimer** [comment]
Ahh yeah, that makes sense. Thanks for your help. I'll find a fix for this.

**Comment by dustinlarimer** [comment]
The queue is accessible at `client.queue`. I could expose a simple method to clear or stop that interval. Would that do the trick?

**Comment by gfpacheco** [comment]
Yes, that would do the job!

**Comment by philkunz** [comment]
normal exiting is like a mandatory feature...

**Comment by dustinlarimer** [comment]
@gfpacheco I have a PR ready for this: https://github.com/keen/keen-tracking.js/pull/80. If you wouldn't mind giving it a quick glance I'd love to hear your thoughts on the update. Hopefully this addresses all the requirements you're looking for. 

Thank you so much for helping me spot this issue, and apologies for the time you lost debugging this! Any other suggestions or observations you care to share would be super helpful 🚀

**Comment by dustinlarimer** [comment]
@philkunz you're totally right, super bummed to see a bug like this sneak out 😞

**Comment by gfpacheco** [comment]
That's great! I just tested and it works just fine.

**Comment by dustinlarimer** [comment]
Awesome! Happy to hear that 😀
