### ISSUE TITLE
Script error binding locks up browsers with selective script blocking extensions

### ISSUE THREAD

**Issue by gavinsmith** [keen/keen-tracking.js#77]
- Install the [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) Chrome extension.
- Visit http://parachutehome.com with the dev tools Network tab open.
- Observe as the page attempts to load the same script, `keen-tracking-1.1.3.min.js`, as many times as it can per second, completely locking up the tab process indefinitely (unless you're very patient, this usually means killing the whole browser process and all tab memory). On my MacBook Pro that's 200k times in 5-10 minutes.

I believe the reason is this line: https://github.com/keen/keen-tracking.js/blob/master/lib/browser-async.js#L8

`s.onload = s.onerror = s['onreadystatechange'] = function () { ...`

I think that `onerror` binding is causing the blocked script to attempt to load in perpetuity when something like uBlock is intercepting the request. This is obviously not okay.

I'd suggest simply killing the `onerror` binding, I can't think why it'd be necessary.

![image](https://user-images.githubusercontent.com/465932/29226852-9cf639d4-7ea1-11e7-8dac-9ff595b999f7.png)

**Comment by dustinlarimer** [comment]
Wow, nice find @gavinsmith -- I agree, I can't think of why that `onerror` is necessary. Perhaps legacy from an earlier loader. We'll investigate and kick out a fix.
