### ISSUE TITLE
Add keen-web-autocollector to this repo

### ISSUE THREAD

**Issue by twiggy** [keen/keen-tracking.js#83]
I'm not seeing the web auto collector in any of the keen repos. Maybe I'm blind. I think it just sits on top of keen-tracking. It works great, but I think I need to extend it a bit to add some autofill type features. keen-tracking can pretty much be setup to do what it is doing, but it'd be nice to start somewhere a little higher up.

I can see the non minified code at https://d26b395fwzu5fz.cloudfront.net/keen-web-autocollector-1.0.8.js , but it is all webpackified. Be nice to see the source source.

Thanks!

**Comment by dustinlarimer** [comment]
@twiggy thanks for the note – I agree, it makes sense to publish this source here, though I can't commit to a timeline to when this will get picked up just yet.

**Comment by dustinlarimer** [comment]
@twiggy just wanted to share that this work is happening here: https://github.com/keen/keen-tracking.js/pull/87 -- any thoughts or feedback would be most appreciated 👍
