### ISSUE TITLE
JSON.parse is called on invalid json (response from sendEventData)

### ISSUE THREAD

**Issue by joaoreynolds** [keen/keen-tracking.js#88]
I got the following error on my production server today:
```shell
<html> 
^ 
SyntaxError: Unexpected token < in JSON at position 0 
    at JSON.parse (<anonymous>) 
    at IncomingMessage.<anonymous> (/app/node_modules/keen-tracking/lib/record-events-server.js:206:22) 
```

The error occurs at `/app/node_modules/keen-tracking/lib/record-events-server.js:206:22` where you have: `var res = JSON.parse(body), error;`

It's been my experience that you should always wrap any call to `JSON.parse` in a `try/catch` block.

I'm sure that's not enough for a fix - seems like the keen server is returning an html body instead of json - so you might have a bigger issue here, and I'm not even sure if I was sending something invalid in my request (because the error, as you can see, cannot be parsed).

**Comment by dustinlarimer** [comment]
@joaoreynolds thanks for reporting 👍  and good call on the `try/catch` -- we did this work on keen-analysis.js but haven't included that here yet: https://github.com/keen/keen-analysis.js/blob/master/lib/utils/http-server.js#L45

Can you share more info on the request that triggered this? I haven't heard of HTML content being returned by our API for any reason, but perhaps there was an encoding issue with the URL? Very strange... happy to chat private via email if you prefer not to share publicly: dustin@keen.io

**Comment by joaoreynolds** [comment]
@dustinlarimer I sent you an email. Thanks!

**Comment by dustinlarimer** [comment]
**UPDATE:** Confirmed, there are rare circumstances where this can happen. We will implement the `try/catch` block in our next release to mitigate the error/failure's impact.

Thanks for your help @joaoreynolds!

**Comment by dustinlarimer** [comment]
@joaoreynolds Including a patch for this in #87

**Comment by joaoreynolds** [comment]
Thanks! This error didn't crash my app as it occurs after the response is sent, so it hasn't been a critical problem for me.

**Comment by dlau** [comment]
Our app experienced a series of crashes this morning due to JSON.parse throwing an exception within this event listener.

What's the status on #87  ?

Thanks!

**Comment by joaoreynolds** [comment]
Just happened again for us, fyi. So when you say 
>  there are rare circumstances where this can happen

There may be a more common occurrence of this than you guys thought.

**Comment by dustinlarimer** [comment]
@joaoreynolds @dlau apologies for the glitch – this patch has been published in `keen-tracking@1.3.0`. Thanks for reporting and helping us squash this bug! Please let me know if you encounter any more issues.

I've also shared your posts with our platform eng team to investigate those malformed responses 👍

**Comment by dlau** [comment]
@dustinlarimer  Thanks for the expedient patch!

If your eng team needs data to look at, feel free to reach out to me @ daryl@zenrez.com 👍

**Comment by dustinlarimer** [comment]
FYI: This has been released in `keen-js@4.2.0` as well: https://github.com/keen/keen-js/releases/tag/v4.2.0

**Comment by joaoreynolds** [comment]
All of the sudden today I've been getting flooded with these same errors with no changes to my own code base. I've added some debug statements to see the body of the event that is trying to be logged when this error happens, if it's at all helpful. I see nothing wrong with it, but maybe some requirement changed on your end? Or it's a bug of course :)

```
There was an error recording an event to keen 
SyntaxError: Unexpected token < in JSON at position 0 
    at JSON.parse (<anonymous>) 
    at IncomingMessage.<anonymous> (/app/node_modules/keen-tracking/lib/record-events-server.js:210:25) 
    at emitNone (events.js:110:20) 
    at IncomingMessage.emit (events.js:207:7) 
    at endReadableNT (_stream_readable.js:1059:12) 
    at _combinedTickCallback (internal/process/next_tick.js:138:11) 
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) 
Details provided 
{ 
  "method": "GET", 
  "route": "/organization/:orgId/events/future", 
  "query": {}, 
  "params": { 
    "orgId": "594c44c4de9735000c7857b2" 
  }, 
  "originalUrl": "/organization/594c44c4de9735000c7857b2/events/future", 
  "status": 304, 
  "executionTime": 27.833244, 
  "organization": { 
    "_id": "594c44c4de9735000c7857b2" 
  }, 
  "keen": { 
    "timestamp": "2018-06-29T01:36:57.214Z", 
    "addons": [ 
      { 
        "name": "keen:date_time_parser", 
        "input": { 
          "date_time": "keen.timestamp" 
        }, 
        "output": "timestamp_info" 
      } 
    ] 
  } 
} 
```

**Comment by adamkasprowicz** [comment]
Hi there!
If you use the most recent version of keen-tracking.js - this kind of issue appears only if there is something wrong with our API. Please report this kind of situations immediately here: https://keen.io/support/
Thanks!
