### ISSUE TITLE
Create Example for Vue.js Instrumentation

### ISSUE THREAD

**Issue by dustinlarimer** [keen/keen-tracking.js#89]
Create a Vue.js Plugin example implementation for our `/docs/examples` directory: https://github.com/keen/keen-tracking.js/tree/master/docs/examples

References:
* https://vuejs.org/v2/guide/installation.html
* https://vuejs.org/v2/guide/plugins.html#Writing-a-Plugin

**Comment by tesarwijaya** [comment]
hello @dustinlarimer i might help with this issue, but still confusing with the approach. in this issue you reference using vue plugin but then i see in react example using flux, because i think vue equivalent of flux is vuex. if you want an implementation using vuex, i can help you.

**Comment by dustinlarimer** [comment]
@tesarwijaya thanks for the offer – Vuex looks super cool.. perhaps it might look something like this?

```javascript
const Keen = require('keen-tracking');
const client = new Keen({
  /* Configure */
});
client.extendEvents(() => {
  /* Baseline Data Model */
});

const keenPlugin = store => {
  // called when the store is initialized
  store.subscribe((mutation, state) => {
    client.deferEvent('app-actions', {
      'mutation': mutation,
      'state': state
    });
  });
};
```

Is there a better approach to this? Vue.js is rather new to me, so if you have any suggestions I'd love to hear them! Perhaps there are multiple instrumentation strategies to cover in addition to Vuex?

**Comment by tesarwijaya** [comment]
that's exactly what i want to try. and i think that is ideal to approach.

**Comment by dustinlarimer** [comment]
Great! If you would like to tackle it, then go right ahead :rocket:

**Comment by tesarwijaya** [comment]
gonna make PR asap :thumbsup:

**Comment by dustinlarimer** [comment]
@tesarwijaya thanks for your help on this! Please shoot an email to dustin@keen.io 👍
