### ISSUE TITLE
Port Examples for Video Instrumentation

### ISSUE THREAD

**Issue by dustinlarimer** [keen/keen-tracking.js#91]
These guides should be ported into this repo as example content and improved to make use of the latest and greatest helpers and utilities: https://keen.io/docs/streams/video-tracking/

Let's create and link to jsFiddles for each one as well.

References:
* [Facebook video player](https://keen.io/docs/streams/video-tracking/#facebook-video-tracking)
* [Youtube video player](https://keen.io/docs/streams/video-tracking/#youtube-video-tracking)
* [VideoJS video player](https://keen.io/docs/streams/video-tracking/#video-js-video-tracking)
* [HTML video player](https://keen.io/docs/streams/video-tracking/#html5-video-tracking)
* [Vimeo video player](https://keen.io/docs/streams/video-tracking/#vimeo-video-tracking)

**Comment by dustinlarimer** [comment]
I'm tackling this one, since we have specific formatting requirements for these examples.

**Comment by tbarn** [comment]
@dustinlarimer The question is... do you get a free Keen IO for your contribution? 😆
